---
abstract: 'Provides an XS implementation for part of Math::Derivative (and fallsback to Perl for the rest)'
author:
  - 'Mark Aufflick <mark@pumptheory.com>'
build_requires:
  Test::More: 0
  YAML::XS: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Derivative_XS
no_index:
  directory:
    - t
    - inc
requires:
  Math::Derivative: 0
version: 0.02
